import Footer from "@/components/customs/Footer";
import Header from "@/components/customs/Header";
import { frFR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={frFR}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-gray-900 via-gray-800 to-gray-900 text-gray-100 flex flex-col min-h-screen`}
        >
          <div className="flex1 flex flex-col p-4 sm:p-8">
            <Header />
            <main className="flex-1 flex flex-col ">{children}</main>
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
